#!/bin/bash

ssh root@45.79.109.251 'bash -s'
docker pull $DOCKER_REGISTRY/$DOCKER_IMAGE_PORTFOLIO:latest
docker stop $DOCKER_CONTAINER_PORTFOLIO || true
docker rm $DOCKER_CONTAINER_PORTFOLIO || true
docker run -d --name $DOCKER_CONTAINER_PORTFOLIO  -p 443:3000 $DOCKER_REGISTRY/$DOCKER_IMAGE_PORTFOLIO:latest
