version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          # command: npm run test
          command: echo Hello, World!!
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Fetch Remote Host SSH Key
          command: |
            ssh-keyscan -H 45.79.109.251 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "b3:f8:90:03:86:2c:83:49:6b:27:e0:e8:72:18:ae:a8"
      - run:
          command: |
            echo "$CIRCLECI_PASSWORD" | sudo -S /usr/bin/rsync -avz -e ~/project/ root@45.79.109.251:~/portfolioSite
          name: Deploy app

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main