version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_deploy:
    docker:
      - image: node:18.17.1-alpine 
    steps:
      - checkout
      - setup_remote_docker:
          version: 24.0.5
      - run:
          name: Build Docker Image
          command: |
            docker build -t portfolio-img:2.0.0 .
      - run:
          name: Push Docker Image to Linode
          command: |
            ssh-keyscan -H 45.79.109.251 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "b3:f8:90:03:86:2c:83:49:6b:27:e0:e8:72:18:ae:a8"
      - run:
          name: Push Docker Image to Linode
          command: |
            docker tag portfolio-img:2.0.0 45.79.109.251/portfolio-img:2.0.0 
            # Replace with your Docker image and registry details
            docker push registry.example.com/portfolio-img:2.0.0
      - run:
          name: Stop and Remove Existing Container
          command: |
            # Replace the following lines with commands to stop and remove the existing container, if any
            docker stop portfolio || true
            docker rm portfolio || true
      - run:
          name: Remove Old Docker Image
          command: |
            # Remove any Docker image with the specified name prefix
            docker rmi $(docker images -q '45.79.109.251/portfolio-img:*') || true
      - run:
          name: Start New Container with Updated Image
          command: |
            # Start a new container with the updated image
            docker run -d --name portfolio -p 3000:3000 45.79.109.251/portfolio-img:2.0.0
          
workflows:
  update_portfolio:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main