version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          # command: npm run test
          command: echo Hello, World!!
          name: Run tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: npm run deploy
          name: Deploy app

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main