version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t portfolio2023:2.0.0 ..
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker image push mjohnst/portfolio2023:2.0.0

workflows:
  update_portfolio:
    jobs:
      - build_and_test
      - build_docker_image