version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t mjohnst/portfolio2023:2.0.0 -t mjohnst/portfolio2023:latest .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker image push mjohnst/portfolio2023:2.0.0
            docker image push mjohnst/portfolio2023:latest

# changed permissions on script         
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy to Linode VPS
          command: |
            ssh root@45.79.109.251 "bash -s" <<EOF
            docker pull mjohnst/portfolio2023:latest
            docker run -d --name portfolio -p 3000:3000 mjohnst/portfolio2023:latest
            EOF

workflows:
  update_portfolio:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
          # filters:
          #   branches:
          #     only: deploy_live
      - deploy:
          requires:
            - build_docker_image