name: UpdateDiscord

on:
  push:
    branches:
      - deploy_live

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get time
        id: time
        run: |
          NOW=$(date +"%Y-%m-%d %H:%M:%S")
          echo "now=${NOW}" >> $GITHUB_ENV
        env:
          TZ: America/Denver

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_SITE_UPDATE_WEBHOOK }}
          content: "Updates arrived at ${{ env.now }}, check it out and see what's changed!"

