name: UpdateDiscord

on:
  pull_request:
    types:
      - closed

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the event is a merge from 'main' to 'deploy_live'
        id: check-merge
        run: echo ::set-output name=is_merged::${{ github.event.pull_request.base.ref == 'deploy_live' && github.event.pull_request.merged == true }}

      - name: Get time
        id: time
        run: |
          NOW=$(date +"%Y-%m-%d %H:%M:%S")
          echo "now=${NOW}" >> $GITHUB_ENV
        env:
          TZ: America/Denver

      - name: Send Discord message
        if: steps.check-merge.outputs.is_merged == 'true'
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_COMMENTS_URL="${{ github.event.pull_request.comments_url }}"
            
          MESSAGE=":white_check_mark: Pull request merged from 'main' to 'deploy_live':
          **Title**: ${PR_TITLE}
          **Comments**: ${PR_COMMENTS_URL}"
  
          curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}" "${DISCORD_WEBHOOK}"